#!/bin/bash
git checkout src/routes/index.tsx
python3 replace_home.py
python3 replace_sections.py
python3 fix.py
python3 fix_btn2.py
python3 fix_all.py
python3 fix_btn.py
python3 fix_sections.py
python3 fix_checklist.py
python3 fix_buttons.py
python3 fix_components.py
python3 fix_components2.py
python3 fix_diagnostico.py
python3 fix_solucoes.py
python3 fix_btn_css.py
python3 update_header_btn.py
python3 fix_final_btn.py
python3 fix_buttons_index.py
python3 fix_btn_header.py
python3 fix_btn_style.py
python3 fix_padding.py
python3 fix_checklist2.py
python3 update_styles.py
python3 fix_sol_btn.py
python3 fix_btn_style2.py
python3 fix_btn_style3.py
python3 fix_words.py
python3 fix_btn_style4.py
python3 fix_autoridade_text.py
python3 fix_autoridade.py
python3 fix_hero_image.py
python3 fix_index_sections.py
python3 fix_index_again.py
python3 fix_processo_bg.py
python3 fix_images.py
python3 fix_divider.py
python3 fix_mobile_and_hub.py
python3 fix_index.py
python3 fix_index_shake.py
python3 fix_syntax.py
python3 fix_syntax2.py
python3 fix_hub_final.py
python3 fix_animated_btn.py
